# Generated by Django 5.0.6 on 2024-05-14 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(max_length=30)),
            ],
            options={
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "db_table": "publisher",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("isbn", models.CharField(max_length=13)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.PositiveIntegerField(default=0)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="book_store.author"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_store.publisher",
                    ),
                ),
            ],
            options={
                "db_table": "book",
            },
        ),
        migrations.CreateModel(
            name="AddToCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_orders",
                        to="book_store.book",
                    ),
                ),
            ],
            options={
                "db_table": "add_to_cart",
            },
        ),
        migrations.CreateModel(
            name="GuestProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guest_profile",
            },
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_product_amount", models.IntegerField(blank=True, default=0)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="checkouts", to="book_store.addtocart"
                    ),
                ),
                (
                    "guest_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="book_store.guestprofile",
                    ),
                ),
            ],
            options={
                "db_table": "check_out",
            },
        ),
        migrations.AddField(
            model_name="addtocart",
            name="guest_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addtocart",
                to="book_store.guestprofile",
            ),
        ),
    ]
